### ISSUE TITLE
Possible regression in client_put2

### ISSUE THREAD

**Issue by barronwaffles** [sepalani/GamestatsHTTP#11] opened 2017-07-02 14:19 UTC
With the introduction of data decoding/encoding in commit b86bcdc9ecfebcf4fa347138b45e098c1ff3373f I've had the database handler throw an exception when client_put2 is called :

`InterfaceError: Error binding parameter 5 - probably unsupported type`

As a (local) temporary fix wrapping/casting the parameter (player_data?) as a string has suppressed the issue.

**Comment by sepalani** [comment] 2017-07-02 14:37
Does this commit fix the issue: https://github.com/sepalani/GamestatsHTTP/commit/1b9c6a63a24277c86797f18146069732fd11ec68
It seems the sqlite module doesn't like bytearrays even if they can be converted into bytes.

Feel free to close the issue if the problem is fixed.

**Closed** 2017-07-02 14:57 UTC
